{
    'name': "traffic",
    'version': '1.0',
    'depends': ['base','website','account'],
    'author': "arthur",
    'category': 'traffic',
    'description': "manage the traffic.",
    'data': [
        'security/ir.model.access.csv',
        'views/traffic_action.xml',
        'views/city_views.xml',
        'views/travel_views.xml',
        'views/booking_views.xml',
        'views/payment_views.xml',
        'views/booking_report.xml',
        'views/agency_views.xml',
        'views/driver_views.xml',
        'views/templates/travel_template.xml',
        'views/templates/recap_template.xml',
        'views/templates/book_template.xml',
        'views/templates/dashboard_template.xml',
        'views/templates/search_template.xml',
        'views/templates/loggin_template.xml',
        'views/templates/loggin_agence_template.xml',
        'views/templates/registration_template.xml',
        'views/templates/planning_template.xml',
        'views/templates/registration_driver_template.xml',
        'views/templates/reservation_template.xml',
        'views/templates/invoicing_template.xml',
        'views/templates/mon_espace_template.xml',
        'views/templates/espace_agence_template.xml',
        'views/type_voyage_views.xml',
        'views/res_partner_views.xml',
        'data/account_account_data.xml',
        'data/product_data.xml',


    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
